name: dart_persistence_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.7
  characters: ^1.3.0
  path: ^1.9.0
  reflectable: ^4.0.5
  sqflite_common_ffi: ^2.3.1
  dart_model:
    git:
      url: https://github.com/DerWolf01/dart_model.git
      ref: main
  postgres: ^3.2.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
