import 'package:dart_store/dart_store.dart';
import 'package:dart_store/data_definition/table/column/column.dart';
import 'package:dart_store/data_definition/table/column/foreign/foreign.dart';
import 'package:dart_store/data_definition/table/column/internal.dart';

/// A class that describes a table.
class TableDescription {
  /// The model type that this table is based on.
  final Type objectType;

  /// The columns that this table has.
  /// These were generated by the class model attributes that were anotated with an [SQLDataType].
  final List<Column> columns;

  /// The @Entity anotation the model was anotated and detected by.
  Entity entity;

  TableDescription(
      {required this.objectType, required this.columns, required this.entity});

  /// The columns that are in a relationship with another table.
  List<ForeignColumn> get foreignKeyColumns =>
      columns.whereType<ForeignColumn>().toList();

  /// The columns that are not the primary key.
  String get internalColumnsSqlNamesWithoutId => columns
      .where(
        (element) => element is InternalColumn && !element.isPrimaryKey,
      )
      .map(
        (e) => e.sqlName,
      )
      .join(", ");

  /// the name of the table.
  String get tableName => entity.name ?? objectType.toString().toSnakeCase();

  /// Returns the column with the given name.
  Column? columnDescription(String columnName) =>
      columns.where((element) => element.sqlName == columnName).firstOrNull;

  /// Returns the columns that have a constraint of type [T].
  List<Column> columnsByConstraint<T extends SQLConstraint>() => columns
      .where((element) => element.constraints.any((element) => element is T))
      .toList();

  /// Returns the columns that have a constraint that extends ForeignKey.
  List<ForeignColumn> foreignColumns() =>
      columns.whereType<ForeignColumn>().toList();

  /// Returns the columns that have a constraint of type [T extends ForeignKey].
  List<ForeignColumn> foreignColumnsByForeignKeyType<T extends ForeignKey>() =>
      foreignColumns()
          .where((element) => element.getForeignKey<T>() != null)
          .toList();

  List<ForeignColumn> manyToManyColumns() => foreignKeyColumns
      .where((element) => element.getForeignKey<ManyToMany>() != null)
      .toList();

  List<ForeignColumn> manyToOneColumns() => foreignKeyColumns
      .where((element) => element.getForeignKey<ManyToOne>() != null)
      .toList();

  List<ForeignColumn> oneToManyColumns() => foreignKeyColumns
      .where((element) => element.getForeignKey<OneToMany>() != null)
      .toList();

  List<ForeignColumn> oneToOneColumns() => foreignKeyColumns
      .where((element) => element.getForeignKey<OneToOne>() != null)
      .toList();

  InternalColumn primaryKeyColumn() => columns.firstWhere(
        (element) => element.isPrimaryKey && element is InternalColumn,
        orElse: () {
          throw Exception("No primary key found for table $tableName");
        },
      ) as InternalColumn;
  @override
  String toString() {
    return 'TableDescription{objectType: $objectType, tableName: $tableName, columns: ${columns.map((e) => e.toString()).toList().join(", ")}}';
  }
}
